[package]
name = "gatekeeper-core"
version = "0.1.0"
edition.workspace = true

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
thiserror = { version = "2.0.12" }
hmac = { version = "0.12.1" }
sha2 = "0.10.9"
bincode = "2.0.1"
base64 = "0.22.1"